apiVersion: apps/v1
kind: Deployment
metadata:
       name: nginx 
specs:
    replicas: 3
    selector: 
      matchLabels: 
          batch:  c39
template: 
     metadata:
         name: nginx 
         labels: 
             batch: c39
      specs:
         containers:
	  - name: nginx 
	     image: nginx 
